/**
******************************************************************************
* @file    UsbMidiClass.h
* @author  apaluch
* @brief   This file is reworked version of usbd_desc.h file generated by stm32cube for CDC USB calss.
******************************************************************************
*
* This software component is licensed by ST under Ultimate Liberty license
* SLA0044, the "License"; You may not use this file except in compliance with
* the License. You may obtain a copy of the License at:
*                      www.st.com/SLA0044
*
******************************************************************************
*/

#ifndef __USBD_MIDI_DESC__C__
#define __USBD_MIDI_DESC__C__

#ifdef __cplusplus
 extern "C" {
#endif

#include "usbd_def.h"

#define         DEVICE_ID1          (UID_BASE)
#define         DEVICE_ID2          (UID_BASE + 0x4)
#define         DEVICE_ID3          (UID_BASE + 0x8)

#define  USB_SIZ_STRING_SERIAL       0x1A

/** Descriptor for the Usb device. */
extern USBD_DescriptorsTypeDef FS_MidiDesc;

#ifdef __cplusplus
}
#endif

#endif /* __USBD_MIDI_DESC__C__ */

