/**
******************************************************************************
* @file    UsbMidiClass.h
* @author  apaluch
* @brief   This file is reworked version of usbd_cdc_if.c file generated by stm32cube for CDC USB calss.
******************************************************************************
*
* This software component is licensed by ST under Ultimate Liberty license
* SLA0044, the "License"; You may not use this file except in compliance with
* the License. You may obtain a copy of the License at:
*                      www.st.com/SLA0044
*
******************************************************************************
*/

#ifndef __USB_MIDI_IF_H__
#define __USB_MIDI_IF_H__

#ifdef __cplusplus
 extern "C" {
#endif

#include <usb/UsbMidiClass.h>

/* Define size for the receive and transmit buffer over MIDI */
#define APP_RX_DATA_SIZE  1024
#define APP_TX_DATA_SIZE  1024

/** MIDI Interface callback. */
extern UsbMidiClass_ItfTypeDef UsbMidiClass_Interface_fops_FS;


uint8_t MIDI_Transmit_FS(uint8_t* Buf, uint16_t Len);

#ifdef __cplusplus
}
#endif

#endif /* __USB_MIDI_IF_H__ */

